version: '3.8'

services:
  grafana:
    image: grafana/grafana:8.4.5
    ports:
      - 3000:3000
    volumes:
      - ./var/grafana/grafana_data:/var/lib/grafana

  loki:
    image: grafana/loki:2.4.2
    ports:
      - 3100:3100
    volumes:
      - ./loki:/etc/loki
    command: -config.file=/etc/loki/loki-config.yml

  promtail:
    image: grafana/promtail:2.0.0
    volumes:
      - ./promtail:/etc/promtail
      - /var/lib/docker/containers:/var/lib/docker/containers
    command: -config.file=/etc/promtail/promtail-config.yml

  flog:
    image: mingrammer/flog
    container_name: flog
    command: -f json -d 10s -l
    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
