version: '3.8'

services:
  grafana:
    image: grafana/grafana:8.4.5
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana

  loki:
    image: grafana/loki:2.4.2
    ports:
      - 3100:3100
    volumes:
      - ./config/loki:/etc/loki
    command: -config.file=/etc/loki/loki-config.yml

  promtail:
    image: grafana/promtail:2.0.0
    volumes:
      - ./config/promtail:/etc/promtail
      - /var/lib/docker/containers:/var/lib/docker/containers
    command: -config.file=/etc/promtail/promtail-config.yml

  app:
    build:
      context: app
      target: production
