version: '3.8'
services:
  app:
    build: ./app
    ports:
      - 5000:3000
    volumes:
      - ./app:/app
  prometheus:
    image: prom/prometheus:v2.34.0
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:8.4.5
    ports:
      - 3000:3000
