version: '3.8'

services:
  grafana:
    image: grafana/grafana:8.4.5
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana

  loki:
    image: grafana/loki:2.4.2
    ports:
      - 3100:3100
    volumes:
      - ./config/loki:/etc/loki
    command: -config.file=/etc/loki/loki-config.yml

  app:
    build:
      context: app
      target: production
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push

  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --address ':9000' --console-address ':9001'
    volumes:
      - ./minio/data:/data
      - ./minio/export:/export
      - ./minio/config:/root/.minio
      - ./minio/policies:/policies

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc rm -r --force myminio/loki;
      /usr/bin/mc mb myminio/loki;
      /usr/bin/mc policy set public myminio/loki;
      exit 0;
      "
